version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-backend
    ports:
      - "8080:8080" # Exponer el backend en el puerto 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/backend_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-db
    networks:
      - backend-network

  postgres-db:
    image: postgres:15
    container_name: postgres-backend
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: backend_db
    ports:
      - "5432:5432" # Exponer PostgreSQL en el puerto 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  pg_data:

networks:
  backend-network:
    driver: bridge
